Done
anatoliyshulika/nodejs-homework pull request #2
Opened 2023-03-15 13:33 UTC by anatoliyshulika

2023-03-15 15:56 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-03-15 15:56 UTC, KhYulian commented on services/checkContactById.js
> +}
checkContactById у цій функції немає потреби. Дуже неоптимально робити такі запити в базу

2023-03-15 15:56 UTC, KhYulian commented on services/shema.js
Цей файл видаліть. Його вміст перенесіть у models/Contact.js

2023-03-15 15:56 UTC, KhYulian commented on models/contacts.js
>  };
```suggestion

 
    return await ContacModel.findOneAndUpdate(
      { _id: contactId },
      { favorite: !contact.favorite },
      { new: true }
    );
    


};
```

2023-03-15 15:56 UTC, KhYulian commented on models/contacts.js
>  };
Якщо контак не знайдено буде повернено null

2023-03-15 15:56 UTC, KhYulian commented on models/contacts.js
>    }
```suggestion


    return await ContacModel.findById(contactId);



  
```

2023-03-15 15:56 UTC, KhYulian commented on models/contacts.js
>    }
якщо не знайдено буде повернено null

2023-03-15 15:56 UTC, KhYulian commented on models/contacts.js
> +  return data;
не змішуйте async/await із then. Використовуйте виключно async/await

2023-03-15 18:20 UTC, KhYulian requested changes
Потрібні ще деякі правки

2023-03-15 18:20 UTC, KhYulian commented on models/contacts.js
>  const listContacts = async () => {
listContacts => getContacts

2023-03-15 18:20 UTC, KhYulian commented on models/contacts.js
> +const ContacModel = mongoose.model("Contact", ContactSchema, "contacts");
ContacModel => Contact

2023-03-15 18:20 UTC, KhYulian commented on models/contacts.js
> +  return data;
Усі ці функції є сервісами їх слід винести окремо. service/contactsService.js

2023-03-15 18:20 UTC, KhYulian commented on routes/api/contacts.js
>      }
```
const contact = await addContact(req.body);
    if (!contact) {
      return   res.status(500).send("Write error"); 
    } 

res.status(201).json(contact);
```

2023-03-15 20:13 UTC, anatoliyshulika commented on models/contacts.js
> +  return data;
Не совсем понял что куда нужно вынести. Тут вроде и так функции по две три строчки??? Или может я не понял что выносить надо?

2023-03-15 22:02 UTC, KhYulian commented on models/contacts.js
> +  return data;
Справа не в тому на скільки великі функції, а в тому, що їм тут не місце) 
getContacts, getContactById, addContact, updateContact, removeContact => service/contactsService.js

2023-03-15 22:03 UTC, KhYulian commented on models/contacts.js
> +  return data;
У вас модель в одному файлі із сервісами. Так робити не варто

2023-03-17 17:15 UTC, anatoliyshulika commented on models/contacts.js
> +  return data;
Полностью переделал.

2023-03-17 18:29 UTC, KhYulian commented on src/controllers/contactController.js
> +});
тільки в getContactById ви використовуєте asyncErrorHandler. Код має бути послідовним. В інших котролерах також варто використати

2023-03-17 18:30 UTC, KhYulian commented on src/controllers/contactController.js
> +// }
Непотрібні коменти видаляйте

2023-03-17 18:30 UTC, KhYulian commented on src/utils/validation.js
> +  }
в цьому немає потреби

2023-03-17 18:31 UTC, KhYulian approved these changes
Чудова робота, коменти візьміть до уваги при роботі над наступною

2023-03-17 18:31 UTC, merged