Hw04 auth
anatoliyshulika/nodejs-homework pull request #3
Opened 2023-03-22 16:44 UTC by anatoliyshulika

2023-03-22 21:46 UTC, KhYulian requested changes
Потрібні правки

2023-03-22 21:46 UTC, KhYulian commented on src/utils/searchParamsRequest.js
> +  return { owner: req.user.id };
```suggestion  
  if (favorite in query) {
    return { owner: req.user.id, favorite: req.query.favorite };
  }
  return { owner: req.user.id };
```

2023-03-22 21:46 UTC, KhYulian commented on src/utils/searchParamsRequest.js
> +function searchParamsRequest(req, res) {
```suggestion
function searchParamsRequest(query) {
```

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +function paginationRequest(req, res) {
```suggestion
function paginationRequest(query) {
```

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +    // eslint-disable-next-line camelcase
використовуйте camelCase perPage

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +  // eslint-disable-next-line camelcase
коменти видаліть

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +    +per_page <= +process.env.MINPERPAGE
змінні середовища непідходяще місце для зберігання minpergae і т.п. просто створіть константу у цьому ж файлі

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +      : +process.env.MAXPERPAGE;
логіка не дуже зрозуміла

2023-03-22 21:46 UTC, KhYulian commented on src/utils/paginationRequest.js
> +  return pagRes;
дуже переускладнено - спростіть

2023-03-22 21:46 UTC, KhYulian commented on src/validators/userValidation.js
> +  });
сзему винесіть в окремий файл

2023-03-22 21:46 UTC, KhYulian commented on src/validators/userValidation.js
> +  }
спершу краще валідувати, щоб не робити запит в бд, якщо дані невалідні

2023-03-27 10:06 UTC, anatoliyshulika commented on src/utils/searchParamsRequest.js
> +  return { owner: req.user.id };
Исправил

2023-03-27 10:36 UTC, anatoliyshulika commented on src/utils/paginationRequest.js
> +function paginationRequest(req, res) {
Не совсем понял с query. Я попробовал, у меня что-то не заработало. Прошу более подобный комментарий.

2023-03-27 10:40 UTC, anatoliyshulika commented on src/utils/paginationRequest.js
> +    // eslint-disable-next-line camelcase
Исправил

2023-03-27 10:40 UTC, anatoliyshulika commented on src/utils/paginationRequest.js
> +  // eslint-disable-next-line camelcase
Исправил

2023-03-27 10:41 UTC, anatoliyshulika commented on src/utils/paginationRequest.js
> +    +per_page <= +process.env.MINPERPAGE
Исправил

2023-03-27 10:42 UTC, anatoliyshulika commented on src/utils/paginationRequest.js
> +  return pagRes;
Исправил

2023-03-27 10:57 UTC, anatoliyshulika commented on src/validators/userValidation.js
> +  });
Исправил

2023-03-27 11:01 UTC, anatoliyshulika commented on src/validators/userValidation.js
> +  }
Исправил

2023-03-28 09:50 UTC, merged